### ISSUE TITLE
In case you need it :)

### ISSUE THREAD

**Issue by MrAntares** [Doddler/RagnarokRebuildTcp#1]
Hi there!

Great work and also, I personally would like to thank you for all those info over the years! It's been a huge help! :)
I just wanted to let you know that if you need help you can use our js client project source as reference (it is a continuation of roBrowser). Not sure if it would be helpful, but just in case, here it is:
https://github.com/MrAntares/Ragna.roBrowser
Also, if you have any comment/question anything you can pop in into our group:
https://discord.com/invite/8JdHwM4Kqm

Regards,
Antares

PS: Sorry I posted an issue but I saw no other way to contact you. You can remove this ofc :)

**Comment by Doddler** [comment]
Ah hey! The roBrowser project helped me a lot so far so it's cool to see others taking it further. If I need to look for reference I'll check out your repo. While I haven't posted in a while, the most reliable way to get ahold of me would be via twitter over at [https://twitter.com/RoDoddler](https://twitter.com/RoDoddler).
