### ISSUE TITLE
Issue generating the CharacterSkill namespace

### ISSUE THREAD

**Issue by joaopedrosgs** [Doddler/RagnarokRebuildTcp#10]
It seems that the CharacterSkill is auto generated, but I'm not sure how to do it. Without this namespace, I cant compile the server

**Comment by Doddler** [comment]
It should be created as part of the GameConfig project which uses the source generator from the project GameConfig.Generator to automatically create the CharacterSkill enumeration on build. Visual studio runs the generator on build automatically for me, though I admit I haven't tried to get it to build in rider.

**Comment by joaopedrosgs** [comment]
Yep, using Visual Studio 2022, it works. Sorry for the trouble!

**Comment by y4my4my4m** [comment]
@Doddler 
Doesn't work for me when using the updateclient.bat
I don't have visual studio.

![Image](https://github.com/user-attachments/assets/1085057a-3f80-4f04-be72-c10b08b6605f)

**Comment by y4my4my4m** [comment]
I kind of got it to build via dotnet build on linux but im still getting type or namespace name "CharacterSkill" could not be found in Unity.
