### ISSUE TITLE
Hard coded path error when running Server

### ISSUE THREAD

**Issue by luislhg** [Doddler/RagnarokRebuildTcp#11]
Hey, congratz on the projects, looks amazing so far.

There is this hard coded path when starting the server.
`System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'F:\ProjectsSSD\RagnarokRebuildTcp\RoRebuildServer\GameConfig\ServerData\Db\EquipmentGroups.csv'.'`

**Comment by luislhg** [comment]
I believe the fix would be, in `DataLoader.cs`, replacing:
```
using var tr = new StreamReader(@"F:\ProjectsSSD\RagnarokRebuildTcp\RoRebuildServer\GameConfig\ServerData\Db\EquipmentGroups.csv") as TextReader;
```
with
```
var inPath = Path.Combine(ServerConfig.DataConfig.DataPath, @"Db/EquipmentGroups.csv");
using var tr = new StreamReader(inPath) as TextReader;
```

**Comment by Doddler** [comment]
This one was previously fixed but I hadn't pushed the update to the repo. It should be working now.
