### ISSUE TITLE
Server error and null Map Exception when creating a new character

### ISSUE THREAD

**Issue by luislhg** [Doddler/RagnarokRebuildTcp#12]
After importing everything from client, and updating addressable.

1. I can start the server "successfully" _(fixed previous hard coded path issue manually)_, however it shows 3 errors... 
![image](https://github.com/user-attachments/assets/2e9242a7-3670-4e2e-a091-d60dad8523da)

2. When creating a character, servers throws an exception
```
Failed to perform LoadCharacterRequest: System.Exception: Could not create player on world map '' as it could not be found.
   at RoRebuildServer.Simulation.World.CreatePlayer(NetworkConnection connection, String mapName, Area spawnArea) in D:\Projects Visual Studio\Github Projects\RagnarokRebuildTcp\RoRebuildServer\RoRebuildServer\Simulation\World.cs:line 349
```
![image](https://github.com/user-attachments/assets/946aa1fa-cb03-409a-9b41-9452800a3d87)
Apparently, map is null for new characters

**Comment by Doddler** [comment]
I guess I broke this when I messed with how character data was saved/loaded, I've pushed out a fix for this.
