### ISSUE TITLE
SkillWindowEntry null exception when logging in a character

### ISSUE THREAD

**Issue by luislhg** [Doddler/RagnarokRebuildTcp#14]
Created a brand new character (manually set a map as the default is null as reported in another issue)
Inside `SkillWindowEntry ` the `skill_nv_basic` is not found thus leaving the `Icon.sprite` null and crashing
![image](https://github.com/user-attachments/assets/d41ce82f-e42d-4959-a27c-3b40bcb280ca)

Commented this line and I was able to login into the game (w/o the proper skills of course) heheh

**Comment by Doddler** [comment]
I've added a check to see if the SkillAtlas returned null and if it did to skip setting the size. Thanks for catching that one!
