### ISSUE TITLE
Hardcoded Path when importing effects from the Client Data folder

### ISSUE THREAD

**Issue by bangbangpoof** [Doddler/RagnarokRebuildTcp#5]
Hi Doddler!

I am currently trying out your solution and i found a hardcoded part ( @$"G:\Projects2\Ragnarok\Resources\data\texture\effect\{e.StrFile}.str" ) in the class EffectStrImporter. I solved it locally in my copy by injecting the dataDir in the Import Method. Hope it also helps others!

**Comment by Doddler** [comment]
Should be fixed.
