### ISSUE TITLE
DataLoader can not load CVS in my Country

### ISSUE THREAD

**Issue by bangbangpoof** [Doddler/RagnarokRebuildTcp#7]
Hi Doddler!

this is the same reason as with the missing monsterclass.json in the DataToClientUtility. In the DataLoader when the CsvReader is initialized it uses CultureInfo.CurrentCulture which does not work in my country. When you use CultureInfo.GetCultureInfo("en-US") it works. i fixed it in my local copy but i wanted to let you know.

**Comment by Doddler** [comment]
I had overlooked that the CSV files might load differently on different systems. I've updated the data loading code and client utility to use InvariantCulture which should produce the same results regardless of the system language and locale settings, and while it's probably not required I now explicitly specify UTF-8 encoding as well.

**Comment by bangbangpoof** [comment]
Looking good, thank you!
